### ISSUE TITLE
noarch packages

### ISSUE THREAD

**Issue by petrushy** [Anaconda-Server/anaconda-client#102]
Hi,

I'm trying to make some documentation packages. These are not architecture dependent so I would like them to be installable on all platforms.

I have used the noarch: True in the meta.yaml file, which then uploads like a any-any architecture and on the web is visible as a source package.

When trying to install it (on my mac) with
conda install -c https://conda.binstar.org/petrush scipy-doc

It seems to find it but when fetching I get an error:
NOT FOUND: https://conda.binstar.org/petrush/osx-64/scipy-doc-0.14.0-0.tar.bz2

It seems like it is adding the "osx-64" architecture to the path, but it should be "any-any" for this package.

**Comment by stephenakearns** [comment]
Closing - consider logging this under the Conda rep
