### ISSUE TITLE
Search API endpoint seems to be capped at 10 results

### ISSUE THREAD

**Issue by anderspitman** [Anaconda-Server/anaconda-client#112]
If you hit the following endpoint:

``https://api.binstar.org/search?name=sphinx``

Only 10 results are returned. I know there are more sphinx packages than that because if I run a more specific query, I still get 10 results:

``https://api.binstar.org/search?name=sphinx-bootstrap``

So it appears to either be capped at 10, or the search algorithm isn't working as I expect. It would be nice to be able to specify the max number of results as a parameter and have the client accept arguments to handle this.

**Comment by stephenakearns** [comment]
tried this again today - API results return 10 items - but if you search Anaconda cloud you get 346 results - https://anaconda.org/search?q=sphinx

**Comment by stephenakearns** [comment]
@mistakevin I think this one may be in progress with a PR? Can you link the PR for this one (or move back to icebox if not addressed?)

**Comment by mistakevin** [comment]
What was the decision on this? Do we increase the number of default results or add an optional size parameter?

**Comment by stephenakearns** [comment]
The decision was to increase the hard-coded cap temporarily to 100 and log a ticket (already done here: #1347 ) to track the work to put in auto-throttling.

**Comment by dsludwig** [comment]
@anderspitman if you visit the URL, you will see 100 results now. We are looking into pagination of the API as well. Thanks for the report!
