### ISSUE TITLE
binstar_client.Binstar.show_channel doesn't work

### ISSUE THREAD

**Issue by pelson** [Anaconda-Server/anaconda-client#114]
Example:

```
>>> from binstar_client.utils import get_binstar
>>> from argparse import Namespace

>>> OWNER = 'pelson'
>>> CLIENT = get_binstar(Namespace(token=os.environ['BINSTAR_TOKEN'], site=None))

>>> print CLIENT.authentication()
{u'last_used': u'2015-01-29T22:20:26.083000+00:00', ... u'scopes': [u'api:build', u'api:build-worker', u'api:modify-collection', u'api:modify-group', u'api:publish', u'api:read', u'api:write', u'file:download', u'npm:download', u'pypi:download', u'pypi:upload'], u'id': u'XXX'}


>>> print CLIENT.show_channel(channel='main', owner=OWNER)
Traceback (most recent call last):
  File "__main__", line 158, in <module>
    print CLIENT.show_channel(channel='main', owner=OWNER)
  File "binstar_client/mixins/channels.py", line 29, in show_channel
    self._check_response(res, [200])
  File "binstar_client/__init__.py", line 160, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: (u'Internal server error', 500)
```

On:

```
$> conda list binstar
binstar                   0.10.1                   py27_1    defaults
```

I understand that the binstar Python API is not stable, and that I should be using the binstar scripts, but I'm in particular need of adding some specific functionality which the CLI cannot yet do.

Am I missing something with show_channel?

It is a separate issue, but the next step which is failing is the use of add_channel, this appears to have a binstar API bug, where *any* distribution within a package is added to the channel, not just the distribution specified. Self contained example can be provided once I've got the show_channel functionality working again.

Thanks!

**Comment by srossross** [comment]
@pelson thanks for reporting this. I will look into this today.

**Comment by pelson** [comment]
@srossross - any progress with this? Have you been able to re-create? Is there anything you need from me? Is the binstar.org API documented anywhere?

**Comment by srossross** [comment]
@pelson sorry for the delay. I have found the issue. I will fix this asap.

**Comment by srossross** [comment]
@pelson this should be fixed now.

**Comment by pelson** [comment]
> @pelson this should be fixed now.

Ah, was it a binstar.org API bug in the end?

Thanks for fixing! I'm going to take another look this evening. There was a problem with using add_channel which I'll see if I can reproduce.

**Comment by stephenakearns** [comment]
closing - legacy issue. Please reopen if still an issue.
