### ISSUE TITLE
Way to query the state of all workers and queues and whatever else we need to monitor

### ISSUE THREAD

**Issue by lilmatt** [Anaconda-Server/anaconda-client#117]
As a sysadmin tasked with keeping binstar up, I need a way to monitor binstar to proactively fix things.

This should be a simple text page with little to no markup. 
"OK" when happy, and something other than "OK" when not.

A second page which can easily give me why things are not "OK" would be helpful, but we wouldn't want it on the initial page. (We could do this with query params as well. Just don't put JS or markup in the page)

If you feel there are things other than workers that should be monitored, pages for them should be made too.

If you are determining worker health by something other than queue size, a page which gives me maximum queue size of the longest queue would be good, so we can set a monitor for "if any queue is longer than 10, warn".

This all also needs a way to disable items from being monitored, for example if you have a new worker which you're debugging but is not in the generally available queue.

Monitoring should also be able to check things like DB health, if backups are happening and are good, etc.

**Comment by stephenakearns** [comment]
closing - updated build UI being released in the next couple of weeks may address.
