### ISSUE TITLE
Windows build workers need to revert to a pristine state between builds

### ISSUE THREAD

**Issue by lilmatt** [Anaconda-Server/anaconda-client#118]
Windows build workers need to revert to a pristine state between builds.
Not doing so gives us trouble such as full disks, and will probably give us other troubles and conflicts eventually.

It is also a security issue to allow users to leave bits and pieces around on the disk between builds.
IIRC, this was one of the justifications to roll our own build tool rather than use Jenkins.

**Comment by tswicegood** [comment]
:+1:

**Comment by stephenakearns** [comment]
We've been working on this - Anaconda-Server/Anaconda-Build#126 - but we are depending on some conda fixes @csoja  :-)
