### ISSUE TITLE
Failure to download package from organization non-standard channe

### ISSUE THREAD

**Issue by ovz** [Anaconda-Server/anaconda-client#137]
Originally posted at https://github.com/Binstar/docs.binstar.org/issues/54. 

I have uploaded a private package to my organization, using non-standard channel test

The page

https://binstar.org/organization/salford_systems/dashboard/channels/test

instructs to use the following command to install a package

conda install -c https://conda.binstar.org/salford_systems/channel/test package

Yet when I run it I get

[salford_wibu_test] C:\spm\git\demo\treenet_api_demo\test>conda install -c https
://conda.binstar.org/salford_systems/channel/test salford_wibu
Fetching package metadata: ....Error: Could not find Binstar user salford_system
s

I get the same error if I try to use a token

[salford_wibu_test] C:\spm\git\demo\treenet_api_demo\test>conda install -c https
://conda.binstar.org/t//salford_systems/t
est package
Fetching package metadata: ...Error: Could not find Binstar user salford_systems

After I added the package to main channel I was able to use both command lines for Public and Private package. This confirms non-standard channel name is the trigger

**Comment by frol** [comment]
@ovz I haven't tried to install a package from a token-URL yet, but I can install a private package with the following command (if I'm logged in):

```
$ conda install -c salford_systems/channel/dev package
```

Full URL (without a token) seems not to work, though, for private packages.

**Comment by frol** [comment]
@ovz URL with token also works fine for me now.

**Comment by stephenakearns** [comment]
stale issue - closing - please reopen if still valid.
