### ISSUE TITLE
Error: Could not find Binstar user noarch

### ISSUE THREAD

**Issue by ovz** [Anaconda-Server/anaconda-client#138]
I created a security token using the following command

```
binstar auth --create \
    --name "my_token" \
    --scopes 'repos conda' \
	-o "my_organization" 
```

I then added it to .condarc on a Windows machine

```
conda config --add channels https://conda.binstar.org/t/token_name/
```

After that when creating an environment

```
conda create --file build/conda/packages.txt --prefix build/conda/Win64 --mkdir --yes --channel my_organization
```

I get the following output ending with an error about user noarch.

<pre>
Fetching package metadata: ......c:\Anaconda\Win64\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
c:\Anaconda\Win64\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
c:\Anaconda\Win64\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
c:\Anaconda\Win64\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
c:\Anaconda\Win64\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
c:\Anaconda\Win64\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
c:\Anaconda\Win64\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
c:\Anaconda\Win64\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Error: Could not find Binstar user noarch
Build step 'Execute shell' marked build as failure
</pre>

**Comment by srossross** [comment]
@ovz  perhaps this is a cona issue @ilanschnell do you have any ideas what this is from?

**Comment by ilanschnell** [comment]
This is basically: https://github.com/conda/conda/issues/1204

**Comment by ovz** [comment]
Thanks guys. I did notice InsecurePlatformWarning too. My issue is "Error: Could not find Binstar user noarch". Note it started to happen only after I added a token as a channel.

Is there at least temporary workaround to make conda create succeed?

**Comment by ovz** [comment]
I've just tested a Linux box. Getting

    Error: Could not find Binstar user noarch

there too.

**Comment by srossross** [comment]
@ovz it looks like the channel name is invalid
```
conda config --add channels https://conda.binstar.org/t/token_name/
```
should be:
```
conda config --add channels https://conda.binstar.org/t/token_name/USERNAME
```

**Comment by ovz** [comment]
Thanks @srossross. For now I worked this around by using explicit binstar login. Would be good to have a complete example how to use tokens to upload private packages with no binstar login required.

**Comment by stephenakearns** [comment]
the first conda issue above was addressed in July - closing as stale issue. please reopen if still a concern.
