### ISSUE TITLE
Add package deletion to the News Feed

### ISSUE THREAD

**Issue by FvD** [Anaconda-Server/anaconda-client#140]
When I delete a package from binstar.org and then try to follow the link to the package from the News Feed I get the standard 404 error screen. But there is nothing that gives me an indication that I have in fact deleted that package.

A "this package was deleted" message instead of the 404 would perhaps be the most user-friendly. An alternative could be to list the deletion action in the News Feed.

**Comment by srossross** [comment]
Great Idea, thanks.

**Comment by stephenakearns** [comment]
@goanpeca - do you know if this issue can be closed. @srossross thought we may have addressed it?

**Comment by goanpeca** [comment]
Yes we have addressed this some time ago in [PR#459](https://github.com/Anaconda-Server/anaconda-server/pull/459)
