### ISSUE TITLE
Releases missing on pypi

### ISSUE THREAD

**Issue by craigbruce** [Anaconda-Server/anaconda-client#147]
As per the docs we install via `pip install binstar` (as we are not in an anaconda environment). 0.10.2 and 0.10.3 are only available on GitHub, not PyPI (https://pypi.python.org/pypi/binstar).

Please can you ensure you upload to pypi when you publish new releases?

**Comment by stephenakearns** [comment]
This has been addressed. Our standard release process includes uploading to PyPI

**Comment by jakirkham** [comment]
Is this still the case? Seems a bit out-of-date on PyPI. Namely PyPI has 1.2.2 and 1.6.5 is the most recent tag.
