### ISSUE TITLE
Confusion over the version of binstar

### ISSUE THREAD

**Issue by craigbruce** [Anaconda-Server/anaconda-client#148]
The version is set in multiple places, all of which can be wrong:

```
$ pip install https://github.com/Binstar/binstar/archive/0.10.3.tar.gz
$ pip list
binstar (dev)
>>> binstar_client.__version__
u'0.8'
```

**Comment by tswicegood** [comment]
Ping @ilanschnell @srossross.

**Comment by ilanschnell** [comment]
When you install binstar using conda
```
conda install binstar
```
, instead of pip.  The version is correct.

**Comment by bryevdv** [comment]
Surely it should be made to work correctly, regardless of how it is installed?

**Comment by craigbruce** [comment]
@bryevdv that would be my preference. Plus both methods are documented as valid installation routes: http://docs.binstar.org/#GettingStarted

**Comment by ilanschnell** [comment]
@srossross I think the project should use versioneer, like most of our other projects do.

**Comment by bryevdv** [comment]
+100

**Comment by srossross** [comment]
Versioneer sounds great

**Comment by tswicegood** [comment]
I'm going to have to be the negative person here -- a massive :-1: on versioneer.  Unless I've missed something obvious in how it works, it makes it impossible to release a development version of your software that has a minor version number +1 from the current release (i.e., current release is 1.2.3, next dev release is 1.3.0alpha) without a bunch of superfluous tags.

**Comment by bryevdv** [comment]
We do exactly that for Bokeh? It's not built into versioneer but nothing in versioneer prevents it from happening.

**Comment by ilanschnell** [comment]
@tswicegood when you say "release a development version", then you are talking about a "release", and all releases should be tagged.  Versioneer also sets very meaningful versions when the git repo is not taggeg, which include the number of commits after the last build, and a few digits of the commit hash.

**Comment by tswicegood** [comment]
@ilanschnell when I say development version, think nightly.  I shouldn't have to create a `1.3.0alpha` tag to say this was the start of the next version of software that is officially released at 1.2.0.  That said, we've hijacked this thread to talk theory.  There's a legitimate bug that needs to be fixed.  There's code in the repository that's broken in a pretty significant way, it shouldn't be.

**Comment by ilanschnell** [comment]
Why do you want to release the development version as `1.3.0alpha` ?  To me, `1.3.0alpha` is an official alpha release of the software, which should be tagged as such.

**Comment by teoliphant** [comment]
@tswicegood Do you have alternative fix for the problem besides using versioneer?   @srossross Do @tswicegood concerns change your mind about using versioneer inside binstar_client?

**Comment by asmeurer** [comment]
I thought the whole point of versioneer was to reasonably version "nightly" builds.

**Comment by srossross** [comment]
I think that there are lots of different and valid ways to do versioning. Currently I have a [simple script (make_version.py)](https://github.com/Binstar/binstar/blob/master/make_version.py) that does the same functionality as versioneer. (adds binstar_client/_version.py) I did not know about versioneer at the time so I did not use it.

To be clear, versioning in binstar is working correctly for pip and conda installs:

```
(vtest)mr_chomps:chalmers sean$ conda list | grep binstar
binstar                   0.10.1                    <pip>
(vtest)mr_chomps:chalmers sean$ pip freeze | grep binstar
binstar==0.10.1
(vtest)mr_chomps:chalmers sean$ python -c "import binstar_client; print binstar_client.__version__"
0.10.1
```

But it does not work for development installs built without running make_version.py first.  This is what  versioneer adds. I would recommend this path forward.

**Comment by tswicegood** [comment]
@teoliphant my recommendation is that the version numbers are maintained directly in `setup.py` (or `binstar.__version__` which is could be imported by `setup.py`).  I've yet to see a compelling use-case for versioneer that conda-build plus GIT_* build strings can't fix.

**Comment by bryevdv** [comment]
@tswicegood Here is why I like versioneer:

* I don't want real, full, actual releases on every CI build, because I don't want thousands (tens of thousands) of releases. If you want every CI build to go through the same release automation that a normal release goes through then I agree versioneer is not for you because it will drastically pollute your GH tag space. 

* I want developers to be able to report very precise version information about their current *working copy* (i.e. *not* a release) and that is what versioneer provides, with a commit count since the last release tag as well as a short hash (and whether the tree is dirty or not)

* I also need to build sdists, which mean conda-build does not help at all

* I really hate the idea of having setup.py (or some imported proxy) be edited *all the time* That is just a personal preference but it is a strong one.

**Comment by malev** [comment]
We have versioneer installed already https://github.com/Anaconda-Server/conda-server/commit/900d830778e32664fb0468b95a59c3ef6fbc7862
