### ISSUE TITLE
Update README.md to use docs.anaconda.org instead of readthedocs

### ISSUE THREAD

**Issue by malev** [Anaconda-Server/anaconda-client#165]

**Comment by stephenakearns** [comment]
@electronwill - assuming this is no longer an issue, but if it is, LMK

**Comment by electronwill** [comment]
Yeah, looks like this was fixed in https://github.com/Anaconda-Server/anaconda-client/commit/3ac91d6750312e3660dd4b259642cae69309f1f3#diff-04c6e90faac2675aa89e2176d2eec7d8 and closing it is the right thing to do.
