### ISSUE TITLE
Uploading private packages to custom channels

### ISSUE THREAD

**Issue by ovz** [Anaconda-Server/anaconda-client#167]
I've also posted this question at binstar.org dashboard.

I need to make my package available only to a specific set of users. Can you please help me put together command-line commands to accomplish the steps below?

* Upload a *new* private package package_project *only* to a custom channel named channel_project.
* Generate a token named token_author that has permissions to upload to channel_project. I assume no other users or token has permissions to upload to channel_project.
* Generate a token named token_client that has permissions to download from channel_project. I assume only token_author and token_client have permissions to download from channel_project.
* Upload an updated package_project *only* to channel_project using token_author.
* Update package_project from channel_project using token_client.

**Comment by srossross** [comment]
Hi @ovz sorry for the delay

To be clear, this method is using binstar.org *channels* which are contained in your a single user account.

> Upload a new private package package_project only to a custom channel named channel_project.

    binstar upload -c channel_project ... file.tar.bz2 

> Generate a token named token_author that has permissions to upload to channel_project. I assume no other users or token has permissions to upload to channel_project.

Right now you can not restrict tokens to channels. I would recommend adding collaborators in the package setting page and use `binstar login`. This eliminates the need to use explicit tokens.

    binstar auth -s api --out ./token_author --name token_author --create

> Generate a token named token_client that has permissions to download from channel_project. I assume only token_author and token_client have permissions to download from channel_project.

This creates a token to allow token downloads. You can not restrict this to individual channels `channel_project` 

    binstar auth -s conda --out ./token_client --name token_client --create

> Upload an updated package_project only to channel_project using token_author.

    binstar upload -t ./token_client -c channel_project ... file.tar.bz2 --user <USERNAME>

> Update package_project from channel_project using token_client.

You will not be able to update a project with token_client because it is a read only token. You can install this package via conda:

     conda install PACKAGE --channel /t/<TOKEN_CLIENT>/<USERNAME>/channel/channel_project 

You can use the same steps as above.

Please see http://docs.anaconda.org/examples.html for reference.

**Comment by ovz** [comment]
Hi @srossross,

Could you please clarify the entry about channels in http://docs.binstar.org/faq.html. I've copy-pasted the entry below. Per your response it is impossible to create a "dev" channel that only dev team can access. Should FAQ be fixed or there’re plans to add per-channel access control?

Channels
Q. What is a channel?

A. Channels are one way Binstar helps you control who can access your packages. When you tag a package as belonging to a specific channel, only users who are listening to that channel will see the package and be able to install it.

By default, all packages you upload are sent to your main channel. However, you could also have a dev channel that only your internal development team can access. You can upload a package to the dev channel, allow other internal users to test it, and then promote it to the main channel when it is ready to be released. You can find more information on channels here.

**Comment by ovz** [comment]
I would like to confirm my understanding of access control principles at binstar.org. It is important for building a packaging system that works for my organization. 

It looks like tokens have much wider permissions than users. Read-only token can install _any_ private package and read-write one can also modify any package. In contrast users have no permissions to packages unless added to a Group in my organization. For each group I can specify privileges to specific packages. 

Privileges to a package automatically grant privileges to every channel.

Is this description accurate? 

I suggest it would be beneficial for the user base to have a comprehensive description how Security Policies work and how they are going to work in the future.

**Comment by srossross** [comment]
> Per your response it is impossible to create a "dev" channel that only dev team can access. Should FAQ be fixed or there’re plans to add per-channel access control?

Yes, the FAQ should be fixed. This will be an available feature in the next few months.

> It looks like tokens have much wider permissions than users. 

Tokens were originally created to interface with conda and pypi urls. tokens `identify` you as a user and you can place some scope restrictions on actions you can perform with a token. `binstar login` creates a token with unlimited scope.

When you are distributing tokens, you are giving limited access to your account.

Now that conda uses the binstar login token, I would recommend solely using binstar groups.
for example these two commands are roughly be equivalent:


```
TOKEN=$(binstar auth --create -n "my token")
conda install -c /t/$TOKEN/ovz
```
and

```
binstar login
conda install -c ovz
```

> Privileges to a package automatically grant privileges to every channel.

correct.


> I suggest it would be beneficial for the user base to have a comprehensive description how Security Policies work and how they are going to work in the future.

Yes, we will work on this.
