### ISSUE TITLE
How can I force conda install from binstar use HTTP instead of HTTPS?

### ISSUE THREAD

**Issue by frol** [Anaconda-Server/anaconda-client#185]
I rebuild Docker images frequently, so I set up HTTP caching proxy on the local network. However, while I can force conda install to use HTTP for official repo by using channel `http://repo.continuum.io/pkgs/free` (notice `http://`), I cannot use this trick for binstar repos because even when I use channels with `http://` prefix (e.g. `http://conda.anaconda.org/asmeurer`). It just redirects to `https://binstar-cio-packages-prod.s3.amazonaws.com/...` and my caching proxy, obviously, doesn't work.

I, certainly, can set up a local mirror, but I would prefer to use a transparent proxy.

**Comment by stephenakearns** [comment]
Anaconda Cloud only supports HTTPS - so this isn't possible.
