### ISSUE TITLE
Uniform CLI and API for "generic" Anaconda Server ur-packages

### ISSUE THREAD

**Issue by malev** [Anaconda-Server/anaconda-client#190]
From @ijstokes:

Anaconda Server has a very generic ur-package model (consisting of things like name, versions, ACL, meta-data). It would be helpful to have a uniform CLI and API to perform standard CRUD operations on these ur-packages without having to have a separate CLI and API for each package type, as seems to currently be the case.
I have promised @srossross that I'll provide more details of the commands I need to execute now and the commands I'd like to execute instead, along with use-case justification. But I don't have time to complete that now.
A few examples I shared in Flowdock. Really needs more organization and commentary, but it's a start:
```
ian$ conda server upload mydemo.py
ian$ conda server upload mynotebook.ipynb
ian$ conda server upload myenvironment.yaml
ian$ conda server upload —replace mydemo.py # replace latest version
ian$ conda server upload mydemo.py # auto-increment version number since it already exists
mary$ conda server download ijstokes/mydemo.py
mary$ conda server download —version 1 ijstokes/mydemo.py # version 1
mary$ conda server download --stdout ijstokes/myenvironment.yaml | conda env create
ian$ conda server upload mydata.dat
ian$ conda server delete —version=1 mydata.dat
```

**Comment by stephenakearns** [comment]
Referencing Anaconda-Server/Anaconda-server#559 - aiming to handle this in this one.
