### ISSUE TITLE
Rename the library into anaconda-client

### ISSUE THREAD

**Issue by malev** [Anaconda-Server/anaconda-client#193]
- [x] Rename repo
- [x] Rename recipe
- [x] Rename sourcecode
- [x] Add executable called **anaconda**

**Comment by jakirkham** [comment]
Will `conda server` still be an option going forward?

**Comment by malev** [comment]
@jakirkham `conda server` should be working but it will be better if you start using it as `anaconda`

**Comment by jakirkham** [comment]
@malev, why not keep the `conda` subcommand going forward? After all, it is working with products of conda-build.

**Comment by malev** [comment]
@jakirkham well, conda has very specific usage now and we wanted to keep it that way. Also, anaconda-client is anaconda.org's clieent, so we feel like the new name makes more sense.

**Comment by jakirkham** [comment]
So, what I like about have a `conda` subcommand(s) is I can run it in any environment. If you switch to `anaconda-client`, I will need to again switch to the `root` environment to run commands. This is a bit tedious when you are building several packages and may want to upload some of them.

**Comment by malev** [comment]
@jakirkham that is actually a good point. Well, you can add:
``` yaml
create_default_packages:
- anaconda-client
```
into your `.condarc`  so you will have `anaconda-client` on every environment that you create.

**Comment by jakirkham** [comment]
Interesting, I hadn't seen this feature before. Thanks for sharing @malev. Couple of follow up questions.

1. Does this result in a fresh install of `anaconda-client` in every environment or is it aliased to the `root` environment somehow?
2. Is `anaconda-client` ok with being installed in a non-`root` environment?
3. Will this result in potentially different versions of `anaconda-client` in different environments?

**Comment by malev** [comment]
1. `conda` will install `anaconda-client` each time in every environment. But! They way `conda` works won't make a fresh installation each time, it will create a hard link to a previous installation. So it will be fast and it won't take extra space from your disk.
2. yes
3. good question and I believe the answer is yes. However I don't see any deprecation release coming soon so you shouldn't have any problem. Also and by the way `conda` works, if you install something else in an environment with a **old** version of `anaconda-client` `conda` will try to update anaconda-client to the latest version.
