### ISSUE TITLE
ServerError when copying package from owner to self

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Server/anaconda-client#196]
When running...

    $ conda server copy r/gcc/4.8.5

I see this error...

    Using binstar api site https://api.anaconda.org
    [ServerError] Internal server error

If I repeat the command, I get this error...

    Using binstar api site https://api.anaconda.org
    [Conflict] The file 4.8.5/linux-32/gcc-4.8.5-1.tar.bz2 already exists, can not copy

**Comment by stephenakearns** [comment]
issue being tracked in Anaconda-Server/docs.anaconda.org#119
