### ISSUE TITLE
conda-server pre-link script expects $PREFIX/.messages.txt to exist

### ISSUE THREAD

**Issue by pelson** [Anaconda-Server/anaconda-client#203]
I can't find the recipe for conda-server (I hope this is the right repo), but the conda-server has a pre-link script which is expecting there to exist a $PREFIX/.messages.txt. This isn't necessarily always available:

```
$ conda create -n _newroot conda-server conda-build setuptools python=2
Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment envs/_newroot:

The following NEW packages will be INSTALLED:

    conda:        3.16.0-py27_0 defaults
    conda-build:  1.17.0-py27_0 defaults
    conda-env:    2.4.2-py27_0  defaults
    conda-server: 0.14.0-1      defaults
    openssl:      1.0.1k-1      defaults
    pip:          7.1.2-py27_0  defaults
    pycosat:      0.6.1-py27_0  defaults
    python:       2.7.10-0      defaults
    pyyaml:       3.11-py27_1   defaults
    readline:     6.2-2         defaults
    requests:     2.7.0-py27_0  defaults
    setuptools:   18.1-py27_0   defaults
    sqlite:       3.8.4.1-1     defaults
    tk:           8.5.18-0      defaults
    wheel:        0.24.0-py27_0 defaults
    yaml:         0.1.6-0       defaults
    zlib:         1.2.8-0       defaults

Proceed ([y]/n)? y

Linking packages ...
pkgs/conda-server-0.14.0-1/bin/.conda-server-pre-link.sh: line 3: 
envs/_newroot/.messages.txt: No such file or directory
Error: Error: pre-link failed: conda-server-0.14.0-1 
```

The script is:

```
$ cat pkgs/conda-server-0.14.0-1/bin/.conda-server-pre-link.sh
#!/bin/bash

cat $SOURCE_DIR/share/.conda-server.txt >>$PREFIX/.messages.txt
```

I know I should be using anaconda-client, not conda-server, but just wanted to report the problem for future templates of deprecation messages like this. The obvious fix is to simply touch ``$PREFIX/.messages.txt`` first.

**Comment by malev** [comment]
Hello @pelson, we have renamed `conda-server` into `anaconda-client` so this is the right repo and you can find the recipe in [here](https://github.com/Anaconda-Server/anaconda-client/tree/develop/conda.recipe).
We've been trying to find the right name for the package we believe that we did it. This is the final name, I'm very sorry for the inconviniences.

**Comment by pelson** [comment]
Thanks @malev. That recipe is still [named binstar](https://github.com/Anaconda-Server/anaconda-client/blob/develop/conda.recipe/meta.yaml#L3), so I'm guessing your internal build isn't using that recipe (i.e. there is no pre-link.sh in that recipe either).

**Comment by malev** [comment]
the recipe it is named binstar, that's because the package is called binstar in the CI, we haven't updated that yet. We need to work on some feature in anaconda.org before renaming the name of the recipe.
The `pre-link.sh` in the `conda-server` recipe was installed to show the deprecation warning. The real `anaconda-client`'s recipe is the one that I've linked before

**Comment by pelson** [comment]
> the recipe it is named binstar, that's because the package is called binstar in the CI

Yet I type ```conda install anaconda-client``` to install anaconda-client. That recipe must be somewhere?
