### ISSUE TITLE
Allow optional silencing/jsonifying of "Using API site of ..." message

### ISSUE THREAD

**Issue by PeterDSteinberg** [Anaconda-Server/anaconda-client#221]
Working with anaconda-build's usage of anaconda-client, I have a need to silence and/or jsonify any messages coming out of anaconda-client.  Currently there is a --json output flag PR in anaconda build (https://github.com/Anaconda-Server/anaconda-build/pull/124).  That PR jsonifies anaconda-build output but not all lines can be read as json because of non-json messages from anaconda-client.

**Comment by stephenakearns** [comment]
Hi Peter - can you do me a favor - remove "in progress" and use the pipeline to set it as In Progress. LMK if you have any questions.

**Comment by PeterDSteinberg** [comment]
Closing this issue because I am able to achieve the silencing of messages from anaconda-build.
