### ISSUE TITLE
'anaconda' channel is gone from anaconda.org?

### ISSUE THREAD

**Issue by jchodera** [Anaconda-Server/anaconda-client#223]
It looks like the `anaconda` channel is gone:
https://anaconda.org/anaconda

but has perhaps been replaced by `anaconda-old`?
https://anaconda.org/anaconda-old

Does anyone have any information on what is going on?  Some of our travis testing has suddenly stopped working as a result.

**Comment by srossross** [comment]
Hi @jchodera, Thanks for reporting, we will work on getting the anaconda channel up and running as soon as possible.

**Comment by stephenakearns** [comment]
Hi @jchodera and @srossross - I think this issue is resolved. Closing it, but if there's still an issue, please reopen or let me know.
