### ISSUE TITLE
Revoke of organization token via CLI doesn't work

### ISSUE THREAD

**Issue by jakirkham** [Anaconda-Server/anaconda-client#224]
If I try to do something like this `conda server -r <TOKEN> -o <ORG>`, it fails noting that the named token does not exist. Changing order has no effect. This was incorrect as the token did exist online and I would get an error message trying to create again due to the name already existing.

**Comment by rafaelhbarros** [comment]
`conda server` is deprecated. `anaconda auth` should be used instead. There is still a bug and I'm working on it.
