### ISSUE TITLE
Make --no-register the default for anaconda upload?

### ISSUE THREAD

**Issue by gmarkall** [Anaconda-Server/anaconda-client#231]
Supposing I create a private package on Anaconda.org, and then attempt to upload a package to it, but for some reason the uploaded package name does not match the name of the private package (perhaps because of a typo, or because I did not upload to the correct organisation). Because registering a new package is the default, a new public package gets created, and my private package is now accidentally exposed to the world.

The two ways to avoid ever accidentally exposing a private package are:

* Always make sure the correct package name and organisation are used when uploading packages
* Always pass the `--no-register` flag to `anaconda upload`

Since these two things need to be done with every package upload to ensure package privacy, it is quite plausible that users will, from time to time, fail to do both of these things. It would be safer if not registering packages were the default, and one had to pass an argument (e.g. `--register`) to register a new package, instead of the other way round.

**Comment by Korijn** [comment]
:+1:

**Comment by srossross** [comment]
I am :+1: for this as well. This is moving up in priorities so keep an eye out here for when it gets released.

**Comment by rafaelhbarros** [comment]
This is ready for review to whoever can comment on it.
