### ISSUE TITLE
Change "anaconda.org" references to "Anaconda Cloud"

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-client#233]
there are a small number of textual references in Anaconda Client to anaconda.org (e.g. in the help file text). A quick search reveals the list. Exceptions to this would be actual URL references which can remain.

**Comment by goanpeca** [comment]
Agree, on a side note, do we have a name for our build infrastructure?

I informally call it the **Anaconda Cloud Build System**, maybe a bit verbose and could be just **Anaconda Build System**, we currently just call it builds and are maybe by doing so taking importance out of it.

@stephenakearns ?

**Comment by stephenakearns** [comment]
Quick note - I've been using "Anaconda Build System" - let's use that for
now.

Also, question on this bug - I realized that the client tool would be used
not just for Anaconda Cloud but also for our Enterprise/Workgroup
customers. I was wondering if it's ok for them to see references to
Anaconda Cloud in the Anaconda-client? Might be odd, but I don't have a
good solution for it currently.

On Tue, Nov 10, 2015 at 7:34 AM, Gonzalo Peña-Castellanos <
notifications@github.com> wrote:

> Agree, on a side note, do we have a name for our build infrastructure?
>
> I informally call it the *Anaconda Cloud Build System*, maybe a bit
> verbose and could be just *Anaconda Build System*, we currently just call
> it builds and are maybe by doing so taking importance out of it.
>
> @stephenakearns <https://github.com/stephenakearns> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaconda-Server/anaconda-client/issues/233#issuecomment-155420289>
> .
>



-- 
*Stephen Kearns*
*Product Manager*

*w: (512) 776-1096*
*m: (737) 444-0474*
*t: @stephenakearns*
*skype: stephen.kearns*

**Comment by goanpeca** [comment]
Well... Anaconda Server is the middle ground there I guess, the way I see it we have a product called **Anaconda Server**. 

- When it is hosted and offered by Continuum on the cloud it is called **Anaconda Cloud**
- When it is hosted on a clients own infrastructure we call it **Anaconda Enterprise**

**Comment by srossross** [comment]
Sine the client does not know in advance if it is going to be used for cloud or enterprise, should we just use "anaconda server" or "Anaconda Cloud"

**Comment by ContinuumJira** [comment]
Hi Sean - wherever possible (always?) use the BRAND environment variable so
that it can be set in one location and propagate everywhere on deployment.
Are there places in the code where this is not possible?

On Fri, Nov 27, 2015 at 4:39 PM, Sean Ross-Ross <notifications@github.com>
wrote:

> Sine the client does not know in advance if it is going to be used for
> cloud or enterprise, should we just use "anaconda server" or "Anaconda
> Cloud"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaconda-Server/anaconda-client/issues/233#issuecomment-160223239>
> .
>



-- 
*Stephen Kearns*
*Product Manager*

*w: (512) 776-1096*
*m: (737) 444-0474*
*t: @stephenakearns*
*skype: stephen.kearns*

**Comment by srossross** [comment]
@stephenakearns it looks like you are using the a "continuumJira" account. can you switch to your stephenakearns account?

> Are there places in the code where this is not possible?

Yes. only the code in the server repo has access to the continuum BRAND variable

**Comment by ContinuumJira** [comment]
RIght! Let me check and find out.

On Sun, Nov 29, 2015 at 8:30 PM, Sean Ross-Ross <notifications@github.com>
wrote:

> @stephenakearns <https://github.com/stephenakearns> it looks like you are
> using the a "continuumJira" account. can you switch to your stephenakearns
> account?
>
> Are there places in the code where this is not possible?
>
> Yes. only the code in the server repo has access to the continuum BRAND
> variable
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Anaconda-Server/anaconda-client/issues/233#issuecomment-160501566>
> .
>



-- 
*Stephen Kearns*
*Product Manager*

*w: (512) 776-1096*
*m: (737) 444-0474*
*t: @stephenakearns*
*skype: stephen.kearns*

**Comment by stephenakearns** [comment]
ok - no clue why it's interpreting my replies as Jira...

Can we use a generic reference to Anaconda? (dont specify cloud or entereprise)
