### ISSUE TITLE
Post-commit hook integration with Github Enterprise, etc.

### ISSUE THREAD

**Issue by amccarty** [Anaconda-Server/anaconda-client#239]
We need to consider adding integrations with GH Enterprise, Gitlab, Sourcetree, etc. for enterprise clients behind firewalls.

**Comment by srossross** [comment]
@amccarty thanks for creating this issue. I think this issue belongs in the server repository because I think we are going to tackle this as an "Epic" or "Theme" and we can discuss it privately there.

**Comment by amccarty** [comment]
whoops - misplaced issue  - will move.
