### ISSUE TITLE
remove copy sub-command

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Server/anaconda-client#258]
It doesn't seem like the `anaconda copy` problem (which is server-side) is getting resolved any time soon (https://github.com/Anaconda-Server/anaconda-server/issues/612) so in the mean time the `copy` subcommand should be removed from the `anaconda-client` package so as to not confuse users.  We have had two releases of the client-side package since the functionality was turned off on the server-side.  I don't think we should have any more client package releases until it is fixed.

**Comment by srossross** [comment]
@ian we are actively working on this internally
