### ISSUE TITLE
404 error on the web site when pressing on a link

### ISSUE THREAD

**Issue by Jacob-Barhak-Continuum** [Anaconda-Server/anaconda-client#26]
If you press on the package name that appears on your dashboard a 404 error appears.

I uploaded cliutils from conda build after recipe was created using conda skeleton pypi. It was uploaded for tester3 and I pressed on the messages appearing on the dashboard where cliutils is underlined.

Note that I deleted and reentered the package several times in case it is related.

I hope this is easy to reproduce from my description.

**Comment by stephenakearns** [comment]
stale - closing
