### ISSUE TITLE
Error if trying to log using a reserved user.

### ISSUE THREAD

**Issue by goanpeca** [Anaconda-Server/anaconda-client#279]
Using the anaconda client to login with some reserved usernames like

`r`, `conda`, returns a **`internal server error`**.

Maybe we should have a more specific and friendlier type of error. Like, username reserved or whatever.. or even invalid user?

I am using anaconda client to log in from within Anaconda UI Client and showing that error is kinda ugly.

![image](https://cloud.githubusercontent.com/assets/3627835/12771741/87d94982-c9f9-11e5-8590-9f081d62f200.png)

**Comment by srossross** [comment]
@goanpeca I can not reproduce on the command line.  Can you trigger this error again?

**Comment by goanpeca** [comment]
I think it has been fixed but the message had a typo
