### ISSUE TITLE
A-Client: Copy command does not work with --to-label and --from-label

### ISSUE THREAD

**Issue by rolando** [Anaconda-Server/anaconda-client#280]
Hi, I'm using `anaconda-client` `1.2.2` and tried to run the following command without success:

```
$ anaconda copy rolando/mypackage/1.0   --to-owner myorg --from-label dev --to-label dev
[WARNING] Did not copy any files. Please check your inputs with

	anaconda show rolando/mypackage/1.0
```

It turns out anaconda is sending the payload to the API as `to_channel: main, from_channel: main`. So I used the deprecated arguments `--from-channel` and `--to-channel` and it worked as expected.

**Comment by marscher** [comment]
It would also be nice to move packages within a channel from one label to another. If that is already possible, please tell me how to do that.

**Comment by stephenakearns** [comment]
Hi @srossross - can you take a look at this one? I believe that @malev is working on a relase of A-Client very soon that could squeeze a fix in for this if needed
