### ISSUE TITLE
A-Client: give users ability to upload environments to an organization

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-client#294]
Current state: you can upload an environment to your user account on Anaconda Cloud, but NOT to an organization, using conda env command

Future state:
anaconda client supports uploading environments to both user and org

Discuss: 
* [ ] @kalefranz - do you want to deprecate conda-env upload? 

cc: @mrduane @JeremyEnns @srossross @kalefranz @malev @csoja

**Comment by malev** [comment]
Look at #291

**Comment by stephenakearns** [comment]
closing as duplicate
