### ISSUE TITLE
Catch 401 error when having a ~/.netrc file defined

### ISSUE THREAD

**Issue by bkreider** [Anaconda-Server/anaconda-client#296]
From this issue: https://github.com/Anaconda-Server/support/issues/23#issuecomment-191416492

Instead of the current error message, it should check for ~/.netrc and give a different error message to help people catch this.

@dsludwig

**Comment by dsludwig** [comment]
```
session.trust_env = False
```

will disable `.netrc` authentication (as well as environment variables NO_PROXY, HTTP_PROXY, and system proxy configuration).

According to this issue, there is no way to disable *only* `.netrc` configuration: https://github.com/kennethreitz/requests/issues/2773

**Comment by dsludwig** [comment]
There's a documented work-around in the issue, I will go forward with that.

**Comment by bkreider** [comment]
Wow!  That was quick!

**Comment by dsludwig** [comment]
Resolved in #298.
